// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'about': string;
  'buttons': string;
  'measureUnitSpan': string;
  'sizeInput': string;
  'sizeMode': string;
  'sizeModeButton': string;
  'sizeModeItem': string;
  'sizeModeItemActive': string;
  'sizeModeLabel': string;
  'sizeModeLabelActive': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
