// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'about': string;
  'buttons': string;
  'sizeInput': string;
  'sizeMode': string;
  'sizeModeButton': string;
  'sizeModeButtonActive': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
